### PR TITLE
Add consensus statistical test and new web output

### PR DESCRIPTION
**Pull request by mdml**
This is a major and breaking change to HotNet2. A summary of the updates:
- `runHotNet2.py` now accepts multiple network and heat files and automatically runs the consensus procedure, _with the consensus statistical test_. `runHotNet2.py` now outputs a directory with a `{network}-{heat score}/` directory per "single" run, and then a `consensus/` directory with the consensus output.
- All the network-related files (influence matrix, gene index, edge list, permuted networks path, and name) are now stored in the HDF5 network file.
- We now generate web output and visualizations using a Tornado web server in `viz/`. The visualizations now use Bower to install dependencies (whereas previously they were hard-coded). You only have to download and install dependencies once (in the `viz/` directory), and then just point `viz/server.py` to the relevant output directory.

Currently, I can run the whole pipeline from start to finish with the example data, and everything works and looks good. However, there are many things to be done before merging.
1. Test on the TCGA Pan-Cancer data to reproduce the results from the HotNet2 paper.
2. Make sure all sorts of (rarely used) features still work:
   - Display scores are probably broken.
   - The scripts for running HotNet2 piecemeal (e.g. `findThreshold.py`, `makeResultsWebsite.py`) are probably broken.
   - Add back result downloads?
   - Add back heat score summary in visualization, including indicating which genes weren't found in any runs/consensus?
3. Add new, desirable features.
   - Show multiple networks in the consensus visualization.
   - Add hierarchy automatically to the visualizations.
   - Add statistics table for visualizations.
4. Cleanup
   - Reorganization and renaming of files to more accurately describe what they do. Move diffusion processes, largest connected component, etc. to their own functions in `hotnet2/network.py`, and call them from `createPPRMat.py` (renamed to something sensical). 
   - Remove cruft.

### CODE REVIEW

**Comment by mdml** [comment]
The current status is that, with the new code, I can reproduce the results on the test simulated data with the old code _with no heat/significance permutations_. Since the new code has a slightly different way of handling data preprocessing, I had to write a script `convertSimulatedDataToOldFormat.py` to convert it so the current #master code could run on it. However, there are slight differences when I generate the data using the current #master code, and I'm not sure how to explain these or the fact that the significance/heat permutations consistently cause differences.

**Comment by matthewreyna** [comment]
I ran both the old code (`master`) and the new code (`improve-consensus-and-web-output`) on our simulated test data, and I found the same subnetworks at the same \delta values for each code base.  The consensus results were identical with a relatively large number of heat permutations (10,000), but they were slightly different -- one added/missing in one consensus subnetwork -- with a smaller number of heat permutations (1,000).  I repeated the runs with 10,000 heat permutations multiple times with consistent results.  From my perspective, it looks your discrepancy between consensus results from the old code and the new code result from the consensus procedure's sensitivity to the number of heat permutations and not a bug in the code, but it is not clear to me why you would consistently have different consensus results in that case.

As a side note, the new code is much easier to run, and the simulated test data makes it possible to test our entire pipeline in several minutes, both of which are incredibly useful features.

**Comment by mdml** [comment]
@matthewreyna: just pushed a major update and reorganization. The one item left on my agenda for this pull request is adding a new `MINI-README` for you to merge with the current README (ideally moving a lot of info to the wiki). You can start looking through the code in the meantime if you want.

Once we merge this pull request, we should add the following as issues (new features):
* Intermediate runs
* HotNet
* Output website to zip

**Comment by matthewreyna** [comment]
I reproduced the results from the Nature Genetics paper using the updated code, and I added a script and data (networks, beta parameters, heat scores) to reproduce these results.  I also updated the documentation for the updated code.  Let's merge.

**Comment by matthewreyna** [comment]
Note, too that this pull request effectively contains the updates from the other pull requests, so we can discard them.

**Pull request merged**
